/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getConnectors() {
    return invoke()<string[]>("get_connectors")
}

export function searchManga(idx: number, query: string) {
    return invoke()<SearchItem[]>("search_manga", { idx,query })
}

export type SearchItem = { id: string; title: string; description: string; cover_url: string }
